version: '3.5'

# Services
services:

  # PHP FPM Service
  php:
    container_name: php
    build:
      dockerfile: php-dockerfile
      context: .
    volumes:
      - './public/:/var/www/html'
      - './logs/php-logging.conf:/usr/local/etc/php-fpm.d/zz-log.conf'
    depends_on:
      - mariadb

  # Nginx Service
  nginx:
    container_name: web
    image: nginx:latest
    ports:
      - 8081:80
    links:
      - 'php'
    volumes:
      - './public/:/var/www/html'
      - './nginx-conf:/etc/nginx/conf.d'
    depends_on:
      - php

  # MariaDB Service
  mariadb:
    container_name: db
    image: mariadb:10.9
    environment:
      MYSQL_DATABASE: voorbeeld_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: mijn_p@ss#
      MYSQL_ROOT_PASSWORD: 4dy5qwtrsag#!sad
    volumes:
      - './mysqldata:/var/lib/mysql'

# Volumes
volumes:
  mysqldata: